---
- hosts: localhost
  pre_tasks:
    - name: Get User
      set_fact: 
        ansible_local_user: "{{ lookup('pipe', 'id -un') | d(lookup('pipe', 'whoami'), True) | d(lookup('env', 'USER'), True) |  d(lookup('env', 'user'), True) |  d(lookup('env', 'LOGNAME'), True) }}"
        failed_when: ansible_local_user == ''
    - name: Set Home
      set_fact:
        ansible_local_home: "/Users/{{ansible_local_user}}"
        failed_when: ansible_local_home == '/Users/'
  roles:
    - visual-studio-code
    - git
    - oh-my-zsh
    - nvm
    - java