---
    - name: Create directory for go
      file:
        path: "{{ansible_local_home}}/go"
        state: directory
        owner: "{{ansible_local_user}}"
    - name: export paths
      lineinfile:
        path: "{{ansible_local_home}}/.zshrc"
        regexp: '{{ item.regexp}}'
        line: '{{ item.line}}'
      with_items:
        - { regexp: 'export GOPATH', line: 'export GOPATH=$HOME/Go'}
        - { regexp: 'export GOROOT',line: 'export GOROOT=/usr/local/opt/go/libexec' }
        - { regexp: 'export PATH=\$PATH:\$GOPATH/bin', line: 'export PATH=$PATH:$GOPATH/bin' }
        - { regexp: 'export PATH=\$PATH:\$GOROOT/bin', line: 'export PATH=$PATH:$GOROOT/bin' }
    - name: Install go
      homebrew: 
        name: go
        state: latest 

        

